export const TOGGLE_BRANCH_DISPLAY = 'TOGGLE_BRANCH_DISPLAY'

export const SUCCESS_DATA = 'SUCCESS_DATA'

export const ERROR_DATA = 'ERROR_DATA'

export const UPDATE_CURRENT_BRANCH = 'UPDATE_CURRENT_BRANCH'

export const UPDATE_BRANCH_LIST = 'UPDATE_BRANCH_LIST'

export const UPDATE_BRANCH_QUERY_STRING = 'UPDATE_BRANCH_QUERY_STRING'
