export const SET_REPOS = 'SET_REPOS';
export const SELECT_REPO = 'SELECT_REPO';
export const SET_REPO_COLLABORATORS = 'SET_REPO_COLLABORATORS';
export const SET_PAIRING_ROOM = 'SET_PAIRING_ROOM';
export const SET_PAIRING_PARTNER = 'SET_PAIRING_PARTNER';
export const SET_ROLE = 'SET_ROLE';
export const CLEAR_ROLE = 'CLEAR_ROLE';
export const CLEAR_REPOS = 'CLEAR_REPOS';
