export const SET_STREAM_URL = 'SET_STREAM_URL'

export const SET_LOCAL_VIDEO_STREAM_URL = 'SET_LOCAL_VIDEO_STREAM_URL'

export const SET_REMOTE_VIDEO_STREAM_URL = 'SET_REMOTE_VIDEO_STREAM_URL'

export const CLEAR_ALL_URLS = 'CLEAR_ALL_URLS'